### PR TITLE
Removing all use of v62.

### PR DESCRIPTION
**Pull request by Zimmi48**
This was as simple as:

```
$ for f in *.v; do sed -e "s/with v62//g" $f > ${f}_new; mv ${f}_new $f; done
```

### CODE REVIEW

**Comment by aspiwack** [comment]
Lesson for the future: `sed -i`.

Remark: you could get away with it because this file isn't compiled (it uses an older tactic syntax, so it can't).

Question: why are you interested in cleaning up a contrib whose value is mostly historical?

**Comment by Zimmi48** [comment]
Closing as I have sent a set of patches for all contribs to Hugo by e-mail.

**Comment by Zimmi48** [comment]
Maybe this is the reason why I could get away with it in this case but you
can have a look at my PRs on other contribs to see that in most cases it is
also quite trivial to get rid of v62.

I am not interested in cleaning up a contrib that is not compiled. I had no
idea that some contribs were kept unmaintained. I was assuming that this
was compilable with some camlp5 magic trick. If this is just kept for
historical value, why is it in the coq-contribs repo?

The reason why I am doing these changes is (obviously) to get rid of v62 in
the main codebase.

**Comment by herbelin** [comment]
The presence of this uncompiled file `matrix_nat.v` in v7 syntax in the `additions` archive has been indeed not detected when the translator was applied, long time ago. Sorry for the confusion it induced (the remark of @aspiwack was presumably only for the file in v7 syntax - and if not, the reason is indeed to - slightly - simplify the current code of Coq which still refers to base v62).

**Comment by herbelin** [comment]
The presence of this uncompiled file `matrix_nat.v` in v7 syntax in the `additions` archive has been indeed not detected when the translator was applied, long time ago. Sorry for the confusion it induced (the remark of @aspiwack was presumably only for the file in v7 syntax - and if not, the reason is indeed to - slightly - simplify the current code of Coq which still refers to base v62).

**Comment by aspiwack** [comment]
@Zimmi48 Yes, I noticed afterwards (just clicked through, curious, not realising that there was half a dozen such PRs). But I thought I'd leave the comment be since it was possibly an interesting discussion to have.

Seems it has too: should `matrix_nat.v` be deleted? (or, converted and be compiled?)

**Comment by herbelin** [comment]
To tell the truth, I could not resist at translating it. It is basically a copy of matrix.v based on `nat` rather than `Z`. I hesitated to add it to the Makefile and I finally respected the will of the author. The file is not used in the final result which is to finally produce a certified computation of fibonacci numbers by taking the power of a square matrix (using addition chains).

**Comment by Zimmi48** [comment]
While wanting to respect the will of the author is laudable, we also have our own goals in maintaining these contribs. Not including a file in the Makefile although it compiles fine means two things: we could miss additional tests of compatibility, and, more importantly, this file is likely to break again and be unmaintained in the future. There are only IMHO two reasonable options: adding to the Makefile or removing it entirely. 

BTW, sorry for my last post which arrived quite late. I had written it this weekend. For some reason my phone decided to post it only now, together with another comment on a different PR.

**Pull request closed without merging**
